name: CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        required: false
        description: 'Test scenario tags'

jobs:
  printEnv:
    runs-on: ubuntu-latest
    steps:
        - run: env
        - run: echo "${{env.github.GITHUB_REPOSITORY}}"
        - run: echo "${{env.GITHUB_REPOSITORY}}"
        - run: echo "${{github.repository}}"
        - run: echo "${{github.GITHUB_REPOSITORY}}"
  printInputs:
    uses: ./.github/workflows/rw_echo.yml
    with:
      logLevel: ${{github.event.inputs.logLevel}}
      tags: ${{github.event.inputs.tags}}
  printInputs2:
    needs: printInputs
    uses: ./.github/workflows/rw_echo.yml
    with:
      logLevel: ${{github.event.inputs.logLevel}}
      tags: ${{github.event.inputs.tags}}
