name: CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        required: false
        description: 'Test scenario tags'

jobs:
  context_dump:
    runs-on: ubuntu-latest
    steps:
      - name: <DEBUG> Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
        shell: bash
      - name: <DEBUG> Dump GitHub context output
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "myContext=$GITHUB_CONTEXT" >> $GITHUB_OUTPUT
        shell: bash
  printEnv:
    runs-on: ubuntu-latest
    steps:
        - run: env
        - run: echo "${{env.github.GITHUB_REPOSITORY}}"
        - run: echo "${{env.GITHUB_REPOSITORY}}"
        - run: echo "${{github.repository}}"
        - run: echo "${{github.GITHUB_REPOSITORY}}"
  custom_action:
    runs-on: ubuntu-latest
    name: A job to list files and echo
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: ls -lRa
        shell: bash
      - name: foo
        uses: ./.github/actions/list
  printInputs:
    uses: ./.github/workflows/rw_echo.yml
    with:
      logLevel: ${{github.event.inputs.logLevel}}
      tags: ${{github.event.inputs.tags}}
  printInputs2:
    needs: printInputs
    uses: ./.github/workflows/rw_echo.yml
    with:
      logLevel: ${{github.event.inputs.logLevel}}
      tags: ${{github.event.inputs.tags}}
