name: echo2

on:
  workflow_call:
    inputs:
      logLevel:
        required: true
        type: string
      tags:
        required: false
        type: string

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "2-"
          echo "Log level: ${{ inputs.logLevel }}"
          echo "Tags: ${{ inputs.tags }}"
